__title__ = "falco"
__description__ = "Python client and SDK for Falco."
__url__ = "https://github.com/falcosecurity/client-py"
__version__ = "0.3.0"
__author__ = "The Falco Authors"
__author_email__ = "cncf-falco-dev@lists.cncf.io"
__license__ = "Apache 2.0"
__copyright__ = "Copyright 2020 The Falco Authors"
