# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import version_pb2 as version__pb2


class serviceStub(object):
  """This service defines a RPC call
  to request the Falco version.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.version = channel.unary_unary(
        '/falco.version.service/version',
        request_serializer=version__pb2.request.SerializeToString,
        response_deserializer=version__pb2.response.FromString,
        )


class serviceServicer(object):
  """This service defines a RPC call
  to request the Falco version.
  """

  def version(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_serviceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'version': grpc.unary_unary_rpc_method_handler(
          servicer.version,
          request_deserializer=version__pb2.request.FromString,
          response_serializer=version__pb2.response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'falco.version.service', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
